# Generated by Django 2.1.5 on 2019-02-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajax', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='like_num',
            new_name='이름',
        ),
        migrations.AddField(
            model_name='like',
            name='like_user_set',
            field=models.ManyToManyField(blank=True, to='ajax.Like'),
        ),
    ]
