# Generated by Django 2.1 on 2019-01-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190118_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='mainphoto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
