# Generated by Django 2.1.5 on 2019-01-23 04:42

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('main', '0005_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
                ('mainphoto', models.ImageField(blank=True, null=True, upload_to='')),
                ('subphoto', models.ImageField(blank=True, null=True, upload_to='')),
                ('publishedDate', models.DateTimeField(blank=True, null=True)),
                ('modifiedDate', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField()),
                ('locate', models.TextField(null=True)),
                ('phone', models.TextField(null=True)),
                ('insta', models.TextField(null=True)),
                ('tag', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.DeleteModel(
            name='Faq',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
