# Generated by Django 2.1.5 on 2019-01-27 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190123_0442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='lat',
            new_name='경도',
        ),
        migrations.RenameField(
            model_name='cafe',
            old_name='mainphoto',
            new_name='메인사진',
        ),
        migrations.RenameField(
            model_name='cafe',
            old_name='subphoto',
            new_name='서브사진',
        ),
        migrations.RenameField(
            model_name='cafe',
            old_name='content',
            new_name='소개',
        ),
        migrations.RenameField(
            model_name='cafe',
            old_name='lng',
            new_name='위도',
        ),
        migrations.RenameField(
            model_name='cafe',
            old_name='insta',
            new_name='위치',
        ),
        migrations.RenameField(
            model_name='cafe',
            old_name='name',
            new_name='이름',
        ),
        migrations.RenameField(
            model_name='cafe',
            old_name='locate',
            new_name='인스타',
        ),
        migrations.RenameField(
            model_name='cafe',
            old_name='phone',
            new_name='전화',
        ),
    ]
